[package]
name = "svelte-rs"
version = "0.1.0"
authors = ["Levi Laine <shiueo.csh@gmail.com>"]
license = "MIT"
repository = "https://github.com/levish0/svelte-rs"
description = "svelte-rs"
edition = "2024"
rust-version = "1.92.0"

[dependencies]
